env:
  browser: true
  es6: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules: { 
  "quotes": ["error", "double"],
  linebreak-style: ["error", "windows"], 
  "eol-last": 0,
  "no-multiple-empty-lines": ["error", { "max": 1, "maxEOF": 0 }], 
  no-var: "error", 
  "import/prefer-default-export": off,
  "no-restricted-syntax": off,
  "guard-for-in": off,  
 }
 
